use vendas;

SELECT SUM(VALOR) AS Recebimento_Valor
FROM DUPLICATA
WHERE VENCIMENTO BETWEEN '2016-01-01' AND '2016-12-31';

SELECT SUM(VALOR) AS Recebimento_Valor 
FROM DUPLICATA 
WHERE year(VENCIMENTO) = '2016';